### PR TITLE
Add DescriptionSubtitle variant

### PR DESCRIPTION
**Pull request by jangoergens**
Now one can put descriptionSubtitle as a variant into the Description component to have a li subtitle component

### CODE REVIEW

**Comment by jangoergens** [comment]
@Proskynete 
Could you also publish these changes in a new version to npm?

**Comment by jangoergens** [comment]
@Proskynete

**Review by Proskynete — APPROVED** [review]
oh thanks!

**Comment by Proskynete** [comment]
Hey @jangoergens, I have an active PR with some changes, I'm waiting for some people to help me check some errors, especially translations

**Pull request merged**
