### PR TITLE
Add typescript

### PR DESCRIPTION
**Pull request by Proskynete**
### Implement typescript support

- Don't consider the files in the lib folder, because these files are transpiled files. 👀 
- Changed helper function.
- The  `L`, `l` and `ll` options to the `dateFormat` prop are deprecated. ⚠️ 
- Use new `dateFormated` options: `only-number`, `short`, `with-weekday` and `full`. 💯 
- Now all components have their type declaration ❣️

### CODE REVIEW

**Comment by Proskynete** [comment]
@stevending1st Hey how are you?
I tag you in this PR, as I want to ask you to check the simplified Chinese translation please!

**Comment by Proskynete** [comment]
Hey @yukosgiti everything is ok?
Currently, I have this PR where I now use TS, but I realized that I do not have the translation for Turkish, I will be adding it, so I ask you if you can review it

**Review by stevending1st — COMMENTED** [review]
LGTM

**Comment by stevending1st** [comment]
> @stevending1st Hey how are you? I tag you in this PR, as I want to ask you to check the simplified Chinese translation please!

I am honored by @Proskynete‘s  invitation. 
I reviewed the Chinese part and found no bug. 
A lot of files have been modified in this PR, and I want to change the version number to `2.0.0`. 
Here I provide a way to support TypeScript with smaller modifications: 
```TypeScript
// index.d.ts
/// <reference types="react" />

declare module 'vertical-timeline-component-react' {
  type ThemeType = {
    yearColor?: string;
    lineColor?: string;
    dotColor?: string;
    borderDotColor?: string;
    titleColor?: string;
    subtitleColor?: string;
    textColor?: string;
  };
  export interface TimelineProps {
    theme?: ThemeType;
    lang?: 'en' | 'es' | 'de' | 'zh_CN';
    dateFormat?: 'L' | 'l' | 'll';
  }
  export interface YearContentProps {
    startDate: string;
    endDate?: string;
    currentYear?: boolean;
  }
  export interface SectionProps {
    title: string;
  }
  export interface DescriptionProps {
    variant?: string;
    text: string;
  }
  export class Timeline extends React.Component<TimelineProps, any> {}
  export class Container extends React.Component<> {}
  export class YearContent extends React.Component<YearContentProps, any> {}
  export class BodyContent extends React.Component<> {}
  export class Section extends React.Component<SectionProps, any> {}
  export class Description extends React.Component<DescriptionProps, any> {}
}
```

**Comment by Proskynete** [comment]
@stevending1st 
I changed the whole project to TypeScript, so there is no need to declare the `vertical-timeline-component-react` module. This approach would have worked if you wanted to continue to maintain the project with just JavaScript (no longer necessary)

As there are breaking changes, it is necessary to use version 3.

I recommend that you update the version since this will be the one that I will continue to maintain, it is fully compatible with TS and JS, you just have to take into account the change of options allowed in the `dateFormat` prop

**Pull request merged**
